### ISSUE TITLE
AttributeMatrix for Attribute Values Set action is NOT duplicated when Copy Workflow is performed.

### ISSUE THREAD

**Issue by stanalyst** [BEMADEV/Workflow-Extensions#1]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When I tried to copy an existing workflow that had implemented the "Attribute Values Set" action - the new workflow was still pointing at the same instance of the attribute matrix that the original workflow was using. So when I edited the action and changed settings for that action - those changes were mirrored in the original workflow. The only way I could 'sever' the link for the attribute matrix between the 2 workflows was to delete the action from one of the workflows and create a new one.

### Expected Behavior

When using "Copy Workflow" - the settings for the "Attribute Values Set" action should remain unique to the each copy of the workflow type.

### Actual Behavior

When using "Copy Workflow" to duplicate a workflow type - the "Attribute Values Set" action will share an instance of the Attribute Matrix - instead of each having their own version to work from.

### Steps to Reproduce

- Create a new workflow that implements the "Attribute Values Set" action and add a couple rows
- Save the workflow
- Now use "Copy Workflow" to duplicate the workflow
- Edit the "Attribute Values Set" action in the new workflow and change setting for the rows.
- Save new workflow
- Reopen first workflow and note that the original options entered for the action have been replaced with what was entered for the new workflow

### Rock Version

1.16.2.1

### Plugin Version

1.0.5.14

### Client Culture Setting

en-US

**Comment by tcavaletto** [comment]
This is a known core bug, our recommendation is to delete the action with the matrix and re-build it.

**Comment by stanalyst** [comment]
Yeah - that's I ended up doing each time. 

Maybe it's worth adding a note/warning about this behavior in the documentation? https://bema-software.atlassian.net/wiki/external/ODcwNTg1ZjBjN2Y0NDlmZjljNjY3YzU5ZGI0OWNhMmE

**Comment by zackdutra** [comment]
This issue just hit me in a major way while helping another church and is causing me to have to do several hours worth of work to fix the matrix that was edited without my knowledge. This should not be closed without a fix, or without a major warning on the action itself.  Does not work as expected at all.

**Comment by bscottdavis** [comment]
@tcavaletto I would agree with @zackdutra. I ran into this same issue recently as well when I realized that the shared matrix identifier was linked to a couple different workflow types that had been duplicated from the same original workflow type.

The common issue I have seen with this bug is that it somewhat happens behind the scenes such that in each case I thought I was editing the newly created workflow type, not knowing that I was also editing the old workflow type as well. I'm normally testing the newly created workflow type to find issues as it is built, but since the issue gets primarily seen in the original workflow type it is very easy for it to be overlooked.

I'll be sure to delete the newly created action in any new workflows I duplicate but just wanted to advocate for any other users that might come across this same issue in the future.

I don't know if this helps at all but it appears that the core team was able to implement some fixes to core blocks in a related [issue here](https://github.com/SparkDevNetwork/Rock/issues/3768) with [these code changes](https://github.com/SparkDevNetwork/Rock/commit/89b7c64ebfeecb4b7dc8be3b6983ca02aa8256dd). Admittedly these changes are above my head but the developer who made the fix mentioned that "[the implementation was done in such a way that it should be easily reused in other areas or can be overridden by custom implementations](https://github.com/SparkDevNetwork/Rock/issues/3768#issuecomment-595275972)."
